# **CUSTOMER TABLE**

In [2]:
import pandas as pd
import numpy as np

np.random.seed(42)

n_customers = 10000

In [3]:
customer_ids = [
    f"C{i:05d}" for i in range(1, n_customers + 1)
]

In [4]:
ages = np.random.randint(18, 61, n_customers)

In [5]:
genders = np.random.choice(
    ["Female", "Male", "Other"],
    size=n_customers,
    p=[0.65, 0.33, 0.02]
)

In [6]:
city_state = {
    "Kolkata": "West Bengal",
    "Bhubaneswar": "Odisha",
    "Mumbai": "Maharashtra",
    "Delhi": "Delhi",
    "Bengaluru": "Karnataka",
    "Hyderabad": "Telangana",
    "Chennai": "Tamil Nadu",
    "Pune": "Maharashtra",
    "Ahmedabad": "Gujarat",
    "Jaipur": "Rajasthan",
    "Lucknow": "Uttar Pradesh",
    "Patna": "Bihar",
    "Guwahati": "Assam",
    "Indore": "Madhya Pradesh"
}

In [7]:
cities = np.random.choice(
    list(city_state.keys()),
    size=n_customers
)

states = [city_state[city] for city in cities]

In [8]:
signup_dates = pd.to_datetime(
    np.random.choice(
        pd.date_range("2024-01-01", "2025-12-31"),
        size=n_customers
    )
)

In [9]:
customers = pd.DataFrame({
    "customer_id": customer_ids,
    "age": ages,
    "gender": genders,
    "city": cities,
    "state": states,
    "signup_date": signup_dates
})

In [10]:
customers.head()

  customer_id  age  gender         city        state signup_date
0      C00001   56  Female         Pune  Maharashtra  2024-02-20
1      C00002   46    Male        Patna        Bihar  2025-05-09
2      C00003   32  Female       Mumbai  Maharashtra  2025-02-12
3      C00004   60    Male  Bhubaneswar       Odisha  2025-09-17
4      C00005   25  Female    Bengaluru    Karnataka  2024-09-29

In [11]:
customers.shape

(10000, 6)

In [12]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  10000 non-null  object
 1   age          10000 non-null  int64
 2   gender       10000 non-null  object
 3   city         10000 non-null  object
 4   state        10000 non-null  object
 5   signup_date  10000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 468.9+ KB

In [13]:
customers.isnull().sum()

customer_id    0
age            0
gender         0
city           0
state          0
signup_date    0
dtype: int64

In [14]:
customers.to_csv("customers.csv", index=False)

# **SELLER TABLE**

In [15]:
n_sellers = 1000

In [16]:
seller_ids = [
    f"S{i:04d}" for i in range(1, n_sellers + 1)
]

In [17]:
seller_cities = np.random.choice(
    list(city_state.keys()),
    size=n_sellers
)

seller_states = [
    city_state[city] for city in seller_cities
]

In [18]:
seller_ratings = np.round(
    np.random.uniform(3.0, 5.0, n_sellers),
    1
)

In [19]:
seller_join_dates = pd.to_datetime(
    np.random.choice(
        pd.date_range("2023-01-01", "2025-12-31"),
        size=n_sellers
    )
)

In [20]:
seller_types = np.random.choice(
    ["Small", "Medium", "Large"],
    size=n_sellers,
    p=[0.60, 0.30, 0.10]
)

In [21]:
sellers = pd.DataFrame({
    "seller_id": seller_ids,
    "seller_city": seller_cities,
    "seller_state": seller_states,
    "seller_rating": seller_ratings,
    "seller_join_date": seller_join_dates,
    "seller_type": seller_types
})

In [22]:
sellers.head()

,seller_id,seller_city,seller_state,seller_rating,seller_join_date,seller_type
0,S0001,Patna,Bihar,3.2,2025-11-19,Small
1,S0002,Delhi,Delhi,4.7,2024-05-01,Small
2,S0003,Mumbai,Maharashtra,3.2,2023-01-28,Large
3,S0004,Bengaluru,Karnataka,3.1,2023-10-15,Small
4,S0005,Ahmedabad,Gujarat,3.7,2024-08-03,Medium

In [23]:
sellers.shape

(1000, 6)

In [24]:
sellers.isnull().sum()

seller_id           0
seller_city         0
seller_state        0
seller_rating       0
seller_join_date    0
seller_type         0
dtype: int64

In [25]:
sellers["seller_type"].value_counts()

seller_type
Small     600
Medium    296
Large     104
Name: count, dtype: int64

In [26]:
sellers.to_csv("sellers.csv", index=False)

# **PRODUCT TABLE**

In [27]:
n_products = 500

In [28]:
product_ids = [
    f"P{i:04d}" for i in range(1, n_products + 1)
]

In [29]:
categories = [
    "Women Fashion",
    "Men Fashion",
    "Beauty",
    "Home & Kitchen",
    "Electronics",
    "Footwear",
    "Jewellery",
    "Kids"
]

In [30]:
product_categories = np.random.choice(
    categories,
    size=n_products,
    p=[0.25, 0.12, 0.12, 0.18, 0.10, 0.10, 0.08, 0.05]
)

In [31]:
subcategory_map = {
    "Women Fashion": [
        "Sarees",
        "Kurtis",
        "Western Wear",
        "Ethnic Wear"
    ],

    "Men Fashion": [
        "Shirts",
        "T-Shirts",
        "Trousers",
        "Ethnic Wear"
    ],

    "Beauty": [
        "Skincare",
        "Makeup",
        "Haircare",
        "Personal Care"
    ],

    "Home & Kitchen": [
        "Kitchenware",
        "Home Decor",
        "Storage",
        "Furniture"
    ],

    "Electronics": [
        "Mobile Accessories",
        "Audio",
        "Smart Devices",
        "Lighting"
    ],

    "Footwear": [
        "Sneakers",
        "Sandals",
        "Slippers",
        "Formal Shoes"
    ],

    "Jewellery": [
        "Earrings",
        "Necklaces",
        "Bracelets",
        "Rings"
    ],

    "Kids": [
        "Kids Clothing",
        "Toys",
        "School Supplies",
        "Baby Products"
    ]
}

In [32]:
product_subcategories = [
    np.random.choice(subcategory_map[category])
    for category in product_categories
]

In [33]:
selling_prices = np.random.randint(
    199,
    5001,
    n_products
)

In [34]:
cost_prices = np.round(
    selling_prices * np.random.uniform(
        0.50,
        0.85,
        n_products
    )
).astype(int)

In [35]:
product_ratings = np.round(
    np.random.uniform(
        3.0,
        5.0,
        n_products
    ),
    1
)

In [36]:
products = pd.DataFrame({
    "product_id": product_ids,
    "category": product_categories,
    "subcategory": product_subcategories,
    "selling_price": selling_prices,
    "cost_price": cost_prices,
    "product_rating": product_ratings
})

In [37]:
products.head()

,product_id,category,subcategory,selling_price,cost_price,product_rating
0,P0001,Jewellery,Bracelets,3142,2404,3.1
1,P0002,Home & Kitchen,Storage,3419,2080,5.0
2,P0003,Women Fashion,Western Wear,367,276,3.1
3,P0004,Women Fashion,Western Wear,1183,672,3.1
4,P0005,Home & Kitchen,Furniture,1306,840,3.6

In [38]:
products.shape

(500, 6)

In [39]:
products.isnull().sum()

product_id        0
category          0
subcategory       0
selling_price     0
cost_price        0
product_rating    0
dtype: int64

In [40]:
products["category"].value_counts()

category
Women Fashion     124
Home & Kitchen     90
Men Fashion        64
Footwear           56
Electronics        55
Beauty             49
Jewellery          41
Kids               21
Name: count, dtype: int64

In [41]:
(products["cost_price"] > products["selling_price"]).sum()

np.int64(0)

In [42]:
products.to_csv(
    "products.csv",
    index=False
)

In [75]:
from google.colab import files
files.download("products.csv")

# **ORDER TABLE**

In [43]:
# =========================
# ORDERS TABLE
# =========================

n_orders = 50000

order_ids = [
    f"ORD{i:05d}" for i in range(1, n_orders + 1)
]

order_customer_ids = np.random.choice(
    customers["customer_id"],
    size=n_orders
)

order_seller_ids = np.random.choice(
    sellers["seller_id"],
    size=n_orders
)

order_product_ids = np.random.choice(
    products["product_id"],
    size=n_orders
)

order_dates = pd.to_datetime(
    np.random.choice(
        pd.date_range("2025-01-01", "2025-12-31"),
        size=n_orders
    )
)

quantities = np.random.choice(
    [1, 2, 3, 4],
    size=n_orders,
    p=[0.65, 0.25, 0.08, 0.02]
)

# Product price lookup
product_price_map = products.set_index(
    "product_id"
)["selling_price"]

order_product_ids = pd.Series(order_product_ids)

unit_prices = order_product_ids.map(
    product_price_map
)

# Discounts
discount_rates = np.random.choice(
    [0, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30],
    size=n_orders,
    p=[0.15, 0.15, 0.20, 0.20, 0.15, 0.10, 0.05]
)

# Correct order value calculation
gross_order_value = unit_prices * quantities

discount_amounts = (
    gross_order_value * discount_rates
)

order_values = (
    gross_order_value - discount_amounts
)

# Delivery
delivery_days = np.random.choice(
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    size=n_orders,
    p=[
        0.08, 0.12, 0.18, 0.20, 0.16,
        0.10, 0.06, 0.04, 0.03, 0.03
    ]
)

# Payment
payment_methods = np.random.choice(
    ["UPI", "COD", "Credit Card", "Debit Card", "Wallet"],
    size=n_orders,
    p=[0.45, 0.30, 0.10, 0.10, 0.05]
)

# Initial order status
order_status = np.random.choice(
    ["Delivered", "Cancelled", "Returned"],
    size=n_orders,
    p=[0.82, 0.10, 0.08]
)

# Create Orders table
orders = pd.DataFrame({
    "order_id": order_ids,
    "customer_id": order_customer_ids,
    "seller_id": order_seller_ids,
    "product_id": order_product_ids,
    "order_date": order_dates,
    "quantity": quantities,
    "unit_price": unit_prices,
    "discount_rate": discount_rates,
    "order_value": order_values,
    "delivery_days": delivery_days,
    "order_status": order_status,
    "payment_method": payment_methods
})

print("Orders shape:", orders.shape)
print("Missing values:", orders.isnull().sum().sum())
print("GMV:", orders["order_value"].sum())
print("AOV:", orders["order_value"].mean())

Orders shape: (50000, 12)
Missing values: 0
GMV: 162493101.35
AOV: 3249.8620269999997

In [44]:
seller_rating_map = sellers.set_index(
    "seller_id"
)["seller_rating"]

orders["seller_rating"] = orders["seller_id"].map(
    seller_rating_map
)

base_probability = 0.08

delivery_effect = np.where(
    orders["delivery_days"] >= 7,
    0.10,
    np.where(
        orders["delivery_days"] >= 4,
        0.04,
        0
    )
)

seller_effect = np.where(
    orders["seller_rating"] < 3.5,
    0.06,
    np.where(
        orders["seller_rating"] >= 4.5,
        -0.03,
        0
    )
)

problem_probability = (
    base_probability
    + delivery_effect
    + seller_effect
)

problem_probability = np.clip(
    problem_probability,
    0.02,
    0.30
)

random_values = np.random.random(n_orders)

problem_order = (
    random_values < problem_probability
)

print(pd.Series(problem_probability).describe())

count    50000.000000
mean         0.119672
std          0.047105
min          0.050000
25%          0.080000
50%          0.120000
75%          0.150000
max          0.240000
dtype: float64

In [45]:
random_values = np.random.random(n_orders)

problem_order = (
    random_values < problem_probability
)

orders["order_status"] = "Delivered"

problem_indices = orders.index[problem_order]

np.random.seed(42)

cancel_indices = np.random.choice(
    problem_indices,
    size=int(len(problem_indices) * 0.55),
    replace=False
)

return_indices = list(
    set(problem_indices) - set(cancel_indices)
)

orders.loc[
    cancel_indices,
    "order_status"
] = "Cancelled"

orders.loc[
    return_indices,
    "order_status"
] = "Returned"

orders["order_status"].value_counts()

order_status
Delivered    44112
Cancelled     3238
Returned      2650
Name: count, dtype: int64

In [46]:
orders["delivery_bucket"] = pd.cut(
    orders["delivery_days"],
    bins=[0, 3, 6, 10],
    labels=["1-3 Days", "4-6 Days", "7-10 Days"]
)

In [47]:
orders["rating_bucket"] = pd.cut(
    orders["seller_rating"],
    bins=[0, 3.5, 4.5, 5],
    labels=["Low Rating", "Medium Rating", "High Rating"]
)

In [48]:
orders["discount_bucket"] = pd.cut(
    orders["discount_rate"],
    bins=[-0.01, 0, 0.10, 0.20, 0.30],
    labels=["No Discount", "1-10%", "11-20%", "21-30%"]
)

In [49]:
orders.to_csv("orders.csv", index=False)

print(orders.shape)
print(orders.columns.tolist())

(50000, 16)
['order_id', 'customer_id', 'seller_id', 'product_id', 'order_date', 'quantity', 'unit_price', 'discount_rate', 'order_value', 'delivery_days', 'order_status', 'payment_method', 'seller_rating', 'delivery_bucket', 'rating_bucket', 'discount_bucket']

# **DERIVED ANALYTICAL FIELD**

In [50]:
seller_rating_map = sellers.set_index(
    "seller_id"
)["seller_rating"]

orders["seller_rating"] = orders["seller_id"].map(
    seller_rating_map
)

In [51]:
orders[[
    "order_id",
    "seller_id",
    "seller_rating"
]].head()

   order_id seller_id  seller_rating
0  ORD00001     S0062            4.4
1  ORD00002     S0745            4.2
2  ORD00003     S0736            4.4
3  ORD00004     S0632            3.4
4  ORD00005     S0565            4.8

In [52]:
base_probability = 0.08

In [53]:
delivery_effect = np.where(
    orders["delivery_days"] >= 7,
    0.10,
    np.where(
        orders["delivery_days"] >= 4,
        0.04,
        0
    )
)

In [54]:
seller_effect = np.where(
    orders["seller_rating"] < 3.5,
    0.06,
    np.where(
        orders["seller_rating"] >= 4.5,
        -0.03,
        0
    )
)

In [55]:
problem_probability = (
    base_probability
    + delivery_effect
    + seller_effect
)

In [56]:
pd.Series(problem_probability).describe()

count    50000.000000
mean         0.119672
std          0.047105
min          0.050000
25%          0.080000
50%          0.120000
75%          0.150000
max          0.240000
dtype: float64

In [57]:
problem_probability = np.clip(
    problem_probability,
    0.02,
    0.30
)

In [58]:
random_values = np.random.random(
    n_orders
)

In [59]:
problem_order = (
    random_values < problem_probability
)

In [60]:
orders["order_status"] = "Delivered"

In [61]:
problem_indices = orders.index[
    problem_order
]

In [62]:
np.random.seed(42)

cancel_indices = np.random.choice(
    problem_indices,
    size=int(len(problem_indices) * 0.55),
    replace=False
)

In [63]:
return_indices = list(
    set(problem_indices) - set(cancel_indices)
)

In [64]:
orders.loc[
    cancel_indices,
    "order_status"
] = "Cancelled"

orders.loc[
    return_indices,
    "order_status"
] = "Returned"

In [65]:
orders["order_status"].value_counts()

order_status
Delivered    44060
Cancelled     3267
Returned      2673
Name: count, dtype: int64

In [66]:
orders.groupby(
    "delivery_days"
)["order_status"].value_counts(
    normalize=True
)

delivery_days  order_status
1              Delivered       0.915136
               Cancelled       0.047146
               Returned        0.037717
2              Delivered       0.914094
               Cancelled       0.045566
               Returned        0.040340
3              Delivered       0.914029
               Cancelled       0.045342
               Returned        0.040629
4              Delivered       0.876661
               Cancelled       0.069070
               Returned        0.054269
5              Delivered       0.877584
               Cancelled       0.070167
               Returned        0.052249
6              Delivered       0.877080
               Cancelled       0.065570
               Returned        0.057349
7              Delivered       0.812129
               Cancelled       0.111074
               Returned        0.076796
8              Delivered       0.827184
               Cancelled       0.086408
               Returned        0.086408
9              Delivered       0.808345
               Cancelled       0.100424
               Returned        0.091231
10             Delivered       0.807717
               Cancelled       0.107260
               Returned        0.085023
Name: proportion, dtype: float64

In [67]:
orders["delivery_bucket"] = pd.cut(
    orders["delivery_days"],
    bins=[0, 3, 6, 10],
    labels=[
        "1-3 Days",
        "4-6 Days",
        "7-10 Days"
    ]
)

In [68]:
cancellation_rate = (
    orders.groupby("delivery_bucket")["order_status"]
    .apply(lambda x: (x == "Cancelled").mean() * 100)
)

cancellation_rate

/tmp/ipykernel_1525/1055012572.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  orders.groupby("delivery_bucket")["order_status"]

delivery_bucket
1-3 Days      4.579552
4-6 Days      6.868996
7-10 Days    10.215254
Name: order_status, dtype: float64

In [69]:
orders["rating_bucket"] = pd.cut(
    orders["seller_rating"],
    bins=[0, 3.5, 4.5, 5],
    labels=[
        "Low Rating",
        "Medium Rating",
        "High Rating"
    ]
)

In [70]:
orders.groupby(
    "rating_bucket"
)["order_status"].value_counts(
    normalize=True
)

/tmp/ipykernel_1525/605192338.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  orders.groupby(

rating_bucket  order_status
Low Rating     Delivered       0.838756
               Cancelled       0.089095
               Returned        0.072149
Medium Rating  Delivered       0.889009
               Cancelled       0.059398
               Returned        0.051592
High Rating    Delivered       0.914911
               Cancelled       0.049594
               Returned        0.035495
Name: proportion, dtype: float64

In [71]:
orders["discount_bucket"] = pd.cut(
    orders["discount_rate"],
    bins=[-0.01, 0, 0.10, 0.20, 0.30],
    labels=[
        "No Discount",
        "1-10%",
        "11-20%",
        "21-30%"
    ]
)

In [72]:
orders.groupby(
    "discount_bucket"
)["order_value"].mean()

/tmp/ipykernel_1525/1821110384.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  orders.groupby(

discount_bucket
No Discount    3789.023938
1-10%          3419.371813
11-20%         3071.467299
21-30%         2743.119077
Name: order_value, dtype: float64

In [73]:
orders.to_csv(
    "orders.csv",
    index=False
)

# **EXCEL SHEET**

In [74]:
from google.colab import files

files.download("orders.csv")

# **LOAD CSV FILES INTO SQL**

In [76]:
import pandas as pd
import sqlite3

orders = pd.read_csv("orders.csv")
products = pd.read_csv("products.csv")

conn = sqlite3.connect("meesho.db")

orders.to_sql("orders", conn, if_exists="replace", index=False)
products.to_sql("products", conn, if_exists="replace", index=False)

print("Tables created successfully!")

Tables created successfully!

In [77]:
pd.read_sql_query("SELECT * FROM orders LIMIT 5", conn)

,order_id,customer_id,seller_id,product_id,order_date,quantity,unit_price,discount_rate,order_value,delivery_days,order_status,payment_method,seller_rating,delivery_bucket,rating_bucket,discount_bucket
0,ORD00001,C00280,S0062,P0124,2025-12-01,1,3765,0.0,3765.0,6,Delivered,UPI,4.4,4-6 Days,Medium Rating,No Discount
1,ORD00002,C00771,S0745,P0052,2025-04-24,1,3942,0.2,3153.6,3,Delivered,UPI,4.2,1-3 Days,Medium Rating,11-20%
2,ORD00003,C05563,S0736,P0333,2025-04-18,1,337,0.2,269.6,3,Delivered,COD,4.4,1-3 Days,Medium Rating,11-20%
3,ORD00004,C00954,S0632,P0430,2025-11-07,3,3206,0.0,9618.0,3,Delivered,Credit Card,3.4,1-3 Days,Low Rating,No Discount
4,ORD00005,C01560,S0565,P0095,2025-11-08,1,4804,0.1,4323.6,3,Delivered,COD,4.8,1-3 Days,High Rating,1-10%

In [78]:
pd.read_sql_query("SELECT * FROM products LIMIT 5", conn)

,product_id,category,subcategory,selling_price,cost_price,product_rating
0,P0001,Jewellery,Bracelets,3142,2404,3.1
1,P0002,Home & Kitchen,Storage,3419,2080,5.0
2,P0003,Women Fashion,Western Wear,367,276,3.1
3,P0004,Women Fashion,Western Wear,1183,672,3.1
4,P0005,Home & Kitchen,Furniture,1306,840,3.6

In [79]:
query = """
SELECT SUM(order_value) AS total_order_value
FROM orders;
"""

pd.read_sql_query(query, conn)

   total_order_value
0       1.624931e+08

In [85]:
query = """
SELECT
    p.category,
    ROUND(SUM(o.order_value), 2) AS total_order_value
FROM orders o
JOIN products p
    ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY total_order_value DESC;
"""

pd.read_sql_query(query, conn)

         category  total_order_value
0   Women Fashion        38357874.50
1  Home & Kitchen        31801237.30
2     Men Fashion        22093255.15
3        Footwear        17127222.05
4          Beauty        16616278.55
5     Electronics        15102465.90
6       Jewellery        13613889.40
7            Kids         7780878.50

In [88]:
query = """
SELECT
    p.category,
    COUNT(o.order_id) AS total_orders
FROM orders o
JOIN products p
    ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY total_orders DESC;
"""

pd.read_sql_query(query, conn)

         category  total_orders
0   Women Fashion         12335
1  Home & Kitchen          9059
2     Men Fashion          6506
3        Footwear          5655
4     Electronics          5387
5          Beauty          4902
6       Jewellery          4067
7            Kids          2089

In [89]:
query = """
SELECT
    p.category,
    ROUND(AVG(o.order_value), 2) AS average_order_value
FROM orders o
JOIN products p
    ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY average_order_value DESC;
"""

pd.read_sql_query(query, conn)

         category  average_order_value
0            Kids              3724.69
1  Home & Kitchen              3510.46
2     Men Fashion              3395.83
3          Beauty              3389.69
4       Jewellery              3347.40
5   Women Fashion              3109.68
6        Footwear              3028.69
7     Electronics              2803.50

In [90]:
query = """
SELECT
    strftime('%Y-%m', order_date) AS month,
    ROUND(SUM(order_value), 2) AS monthly_order_value
FROM orders
GROUP BY month
ORDER BY month;
"""

pd.read_sql_query(query, conn)

      month  monthly_order_value
0   2025-01          13788810.75
1   2025-02          12397203.30
2   2025-03          13714400.25
3   2025-04          13678846.25
4   2025-05          13561873.20
5   2025-06          13425721.10
6   2025-07          13970081.90
7   2025-08          13911123.75
8   2025-09          13205517.20
9   2025-10          14228916.35
10  2025-11          12869222.20
11  2025-12          13741385.10

In [91]:
print(orders.columns.tolist())

['order_id', 'customer_id', 'seller_id', 'product_id', 'order_date', 'quantity', 'unit_price', 'discount_rate', 'order_value', 'delivery_days', 'order_status', 'payment_method', 'seller_rating', 'delivery_bucket', 'rating_bucket', 'discount_bucket']

In [92]:
query = """
SELECT
    payment_method,
    COUNT(order_id) AS total_orders,
    ROUND(SUM(order_value), 2) AS total_order_value
FROM orders
GROUP BY payment_method
ORDER BY total_order_value DESC;
"""

pd.read_sql_query(query, conn)

  payment_method  total_orders  total_order_value
0            UPI         22652        73715215.05
1            COD         14964        48317459.85
2    Credit Card          4971        16423527.30
3     Debit Card          4950        16098331.15
4         Wallet          2463         7938568.00

In [93]:
query = """
SELECT
    order_status,
    COUNT(order_id) AS total_orders,
    ROUND(SUM(order_value), 2) AS total_order_value
FROM orders
GROUP BY order_status
ORDER BY total_order_value DESC;
"""

pd.read_sql_query(query, conn)

  order_status  total_orders  total_order_value
0    Delivered         44060       1.427453e+08
1    Cancelled          3267       1.087570e+07
2     Returned          2673       8.872082e+06

In [94]:
query = """
SELECT
    p.product_id,
    p.category,
    p.subcategory,
    COUNT(o.order_id) AS total_orders,
    ROUND(SUM(o.order_value), 2) AS total_order_value
FROM orders o
JOIN products p
    ON o.product_id = p.product_id
GROUP BY
    p.product_id,
    p.category,
    p.subcategory
ORDER BY total_order_value DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

,product_id,category,subcategory,total_orders,total_order_value
0,P0060,Home & Kitchen,Home Decor,117,749149.10
1,P0226,Electronics,Audio,110,747058.00
2,P0245,Footwear,Sandals,111,726513.90
3,P0084,Footwear,Sneakers,106,722104.60
4,P0139,Footwear,Slippers,111,715782.60
5,P0074,Women Fashion,Sarees,125,713543.95
6,P0434,Footwear,Sneakers,114,710768.00
7,P0040,Home & Kitchen,Storage,103,694728.35
8,P0087,Beauty,Skincare,114,690828.60
9,P0386,Electronics,Mobile Accessories,107,685432.80

In [95]:
query = """
SELECT
    p.category,
    ROUND(SUM(o.quantity * (p.selling_price - p.cost_price)), 2) AS estimated_profit
FROM orders o
JOIN products p
    ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY estimated_profit DESC;
"""

pd.read_sql_query(query, conn)

         category  estimated_profit
0   Women Fashion        14028001.0
1  Home & Kitchen        11524722.0
2     Men Fashion         8390585.0
3        Footwear         6850159.0
4          Beauty         6099376.0
5     Electronics         5328698.0
6       Jewellery         4893513.0
7            Kids         2990214.0

In [96]:
query = """
SELECT
    payment_method,
    COUNT(order_id) AS total_orders,
    SUM(
        CASE
            WHEN order_status IN ('Cancelled', 'Returned')
            THEN 1
            ELSE 0
        END
    ) AS failed_orders,
    ROUND(
        100.0 * SUM(
            CASE
                WHEN order_status IN ('Cancelled', 'Returned')
                THEN 1
                ELSE 0
            END
        ) / COUNT(order_id),
        2
    ) AS non_delivered_rate
FROM orders
GROUP BY payment_method
ORDER BY non_delivered_rate DESC;
"""

pd.read_sql_query(query, conn)

  payment_method  total_orders  failed_orders  non_delivered_rate
0            COD         14964           1789               11.96
1            UPI         22652           2703               11.93
2     Debit Card          4950            582               11.76
3    Credit Card          4971            581               11.69
4         Wallet          2463            285               11.57

In [97]:
query = """
SELECT
    delivery_bucket,
    COUNT(order_id) AS total_orders,
    SUM(
        CASE
            WHEN order_status IN ('Cancelled', 'Returned')
            THEN 1
            ELSE 0
        END
    ) AS failed_orders,
    ROUND(
        100.0 * SUM(
            CASE
                WHEN order_status IN ('Cancelled', 'Returned')
                THEN 1
                ELSE 0
            END
        ) / COUNT(order_id),
        2
    ) AS non_delivered_rate
FROM orders
GROUP BY delivery_bucket
ORDER BY non_delivered_rate DESC;
"""

pd.read_sql_query(query, conn)

  delivery_bucket  total_orders  failed_orders  non_delivered_rate
0       7-10 Days          8037           1491               18.55
1        4-6 Days         22900           2815               12.29
2        1-3 Days         19063           1634                8.57

In [98]:
query = """
SELECT
    rating_bucket,
    COUNT(order_id) AS total_orders,
    SUM(
        CASE
            WHEN order_status IN ('Cancelled', 'Returned')
            THEN 1
            ELSE 0
        END
    ) AS failed_orders,
    ROUND(
        100.0 * SUM(
            CASE
                WHEN order_status IN ('Cancelled', 'Returned')
                THEN 1
                ELSE 0
            END
        ) / COUNT(order_id),
        2
    ) AS non_delivered_rate
FROM orders
GROUP BY rating_bucket
ORDER BY non_delivered_rate DESC;
"""

pd.read_sql_query(query, conn)

   rating_bucket  total_orders  failed_orders  non_delivered_rate
0     Low Rating         13985           2255               16.12
1  Medium Rating         23957           2659               11.10
2    High Rating         12058           1026                8.51

In [99]:
query = """
SELECT
    discount_bucket,
    COUNT(order_id) AS total_orders,
    ROUND(SUM(order_value), 2) AS total_order_value,
    SUM(
        CASE
            WHEN order_status IN ('Cancelled', 'Returned')
            THEN 1
            ELSE 0
        END
    ) AS failed_orders,
    ROUND(
        100.0 * SUM(
            CASE
                WHEN order_status IN ('Cancelled', 'Returned')
                THEN 1
                ELSE 0
            END
        ) / COUNT(order_id),
        2
    ) AS non_delivered_rate
FROM orders
GROUP BY discount_bucket
ORDER BY non_delivered_rate DESC;
"""

pd.read_sql_query(query, conn)

,discount_bucket,total_orders,total_order_value,failed_orders,non_delivered_rate
0,21-30%,7572,20770897.65,966,12.76
1,1-10%,17448,59661199.40,2060,11.81
2,No Discount,7436,28175182.00,877,11.79
3,11-20%,17544,53885822.30,2037,11.61

In [100]:
query = """
SELECT
    p.subcategory,
    COUNT(o.order_id) AS total_orders,
    ROUND(SUM(o.order_value), 2) AS total_order_value
FROM orders o
JOIN products p
    ON o.product_id = p.product_id
GROUP BY p.subcategory
ORDER BY total_order_value DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

    subcategory  total_orders  total_order_value
0   Ethnic Wear          4840        16410893.20
1       Storage          2543         9686726.45
2  Western Wear          3471         9265096.25
3        Sarees          2898         9176381.10
4        Kurtis          3030         9141982.20
5     Furniture          2300         7687643.75
6   Kitchenware          2278         7653878.90
7        Shirts          1775         7099465.05
8    Home Decor          1938         6772988.20
9      Sneakers          1905         6732574.55